{% set version = "0.1.1" %}
{% set commit = "cc684e2e2ee6eea27316b02d32d9b1e3d9ca2554" %}

package:
  name: tikzmagic
  version: {{ version }}

source:
  url: https://github.com/mkrphys/ipython-tikzmagic/archive/{{ commit }}.tar.gz
  sha256: 4e2373b8b04968b4e3cb5db798331027491db1a965dcba928a89ed2c9302311f

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python >=3
    - pip
    # - ipython
  run:
    - python >=3
    - ipython

test:
  imports:
    - tikzmagic

about:
  home: https://github.com/mkrphys/ipython-tikzmagic
  license: BSD-3-Clause
  license_file: COPYRIGHT
  summary: 'Notebook magics for generating figures with TikZ'

extra:
  recipe-maintainers:
    - ocefpaf
