{% set version = "0.1.0" %}
{% set commit = "bcbb04553c06a430192ed6e54f7caade779e7dba" %}

package:
  name: tikzmagic
  version: {{ version }}

source:
  fn: {{ commit }}.tar.gz
  url: https://github.com/mkrphys/ipython-tikzmagic/archive/{{ commit }}.tar.gz
  sha256: db4dab34f419d6931e4870f66d6bc186984ebc0b3371472c2b3d043aedcaa9cd

build:
  noarch: python
  number: 1
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - pip
    - python
    - setuptools
    - ipython
  run:
    - python
    - notebook

test:
  imports:
    - tikzmagic

about:
  home: https://github.com/mkrphys/ipython-tikzmagic
  license: BSD 3-Clause
  license_file: COPYRIGHT
  summary: 'Notebook magics for generating figures with TikZ.'

extra:
  recipe-maintainers:
    - ocefpaf
