travis:
  secure:
    BINSTAR_TOKEN: exZl1JfIESV0QWzcZFElymOGFAehn2MhsBSpLh6JXvQNb1zQeKW3tYgNVPbautfDFh+ySJqhm+OfcaBcWYrrUF9Wo2r6IF6csaPAHousm2/7RHLYuZuslocJAy3Sfl4U4C5OYzTg/LRzwWfTLh5LMi+n7cGWFcwMCJX9cc1BaPsno6f6lab1Bqfg0oe9gsLVBZH2pn2WHAasu1Tg1cTtqgxsA5qX83HTM1GjWcbX8jBsbFLJDbXtDW3ORw8NvplXopG2gsawdR57ZuviiMTsdPRN5x/MiSiSqzfl8O4N87ck+cVGAn9GkBPV5MZYbvR7qoZSx6UQ1Qo4Prg4ZC2/Wy3x19TGnaN/FfMmi0FMJA9RuLmtXFE3o5tuqdXEJH+rWgTKc5l0YQdDNfRuSnms8ebP1kl6lnFE9tbF6AP7CbYVTH33NgvS/J88osds8hIuC7DCKPbAt9tTwbEnJoOw+jChS4/cOWAQLLcgkl4ii/eInvSVY4spt+tt89Z6qhpxm++1CmG8HN9xf4LCSj/E+AnNo36sLH8qBqtxwhL4ojA18ms0Z40u5pRA+9h/syY5tJv4jKJOUgJoCX632kgGaFDBrRjlVMs/XtJGrKvg0zBsMuxpQcboWIltDUYjq4l+E8qNMr4XzQexDAeTWCzL+OTJWM1kDA4N8QEMbr86u98=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: false
