travis:
  secure:
    BINSTAR_TOKEN: N/bWv06bxyCcS6lt7pCbl4ZDXlXisyL52eGJVW2WlIG+TnhACBcgEUxq27GtnI0w1c6HwfIArHU4CQKQLJROQYgDFNvM4lGmmD+SD9W9MtN6L3g+TAFWxPuGZh7OoMaSOF/PFlq8ouIYi/iJbeOXs9XLOtYdSM3CIotxI1wOg7k3et1GPPesmN7hPd8f3UFUrViO15wsMyrfrDs/3ZHE+Y55ZKDzdptEo0WRIJDV3B3j8Hdew8xs/inMfF2KqVmJ5X1i3A8h/q9s6OIw3eZBjEgmQBdd431F7/wrGz4dj4qSCk7AhX4gKZdlDI5mgBzX9J5SFiFOZOK029BDfE93ElC5iPGvkwmY5PWo15jx2peDpUT2N0VdvkVfT1KThRKU7VjvSgEra+wdGA5xPni4NDoRzURkEe1nnnv7AjyfNVTLRWdKq/rA52mH8C3CDISgm3h3ZQGPgi6qrBVUWHrvWVUE+OQLHUBgFOQzKwPteOICE5bI8l4VGDNtonYfVrMnEGSDBRRV3+uRT3InY196W1PH5PK4WMlQXZfFqxFcpVPXBqWBtrmUGLQ/5Sd+grQuRl6k1zAttLo5bJTt9DrpzvEj+LfGnUyZdhpO8RzUJ1kuT3m5lm8NcZ1oppmGDgA0EFGtyBrcI2hcq8PXSy0fYEwHTOXUalqrBN++KK28W2M=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
